import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "Omega Black Edition",
    company: "Omega",
    img: "https://res.cloudinary.com/suyash56565656/image/upload/v1648046434/Front-Fist/assets/Products/Omega%20watches/omega-1_x4m34y.png",
    price: 5000,
    categoryName: "Gent's",
    discount: 10,
    isbadge: "true",
    badge: "New",
    rating: 4,
    stocks: 100,
    inStock: true,
    codAvailable: true,
  },
  {
    _id: uuid(),
    title: "Omega Gold Edition",
    company: "Omega",
    img: "https://res.cloudinary.com/suyash56565656/image/upload/v1648046434/Front-Fist/assets/Products/Omega%20watches/omega-2_oia5y4.png",
    price: 5000,
    categoryName: "Gent's",
    discount: 10,
    isbadge: "true",
    badge: "New",
    rating: 4,
    stocks: 100,
    inStock: true,
    codAvailable: true,
  },
  {
    _id: uuid(),
    title: "Cartier classic edition",
    company: "Cartier",
    img: "https://res.cloudinary.com/suyash56565656/image/upload/v1648046434/Front-Fist/assets/Products/Cartier%20watches/Cartier-1_higpys.png",
    price: 5000,
    categoryName: "Gent's",
    discount: 10,
    isbadge: "true",
    badge: "New",
    rating: 4,
    stocks: 100,
    inStock: true,
    codAvailable: true,
  },
  {
    _id: uuid(),
    title: "Cartier tiger edition",
    company: "Cartier",
    img: "https://res.cloudinary.com/suyash56565656/image/upload/v1648046433/Front-Fist/assets/Products/Cartier%20watches/Cartier-2_mhqh4q.png",
    price: 5000,
    categoryName: "Gent's",
    discount: 10,
    isbadge: "true",
    badge: "New",
    rating: 4,
    stocks: 100,
    inStock: true,
    codAvailable: true,
  },
  {
    _id: uuid(),
    title: "Hublot scrap edition",
    company: "Hublot",
    img: "https://res.cloudinary.com/suyash56565656/image/upload/v1648046433/Front-Fist/assets/Products/Hublot/Hublot-1_vhgvbf.png",
    price: 5000,
    categoryName: "Gent's",
    discount: 10,
    isbadge: "true",
    badge: "New",
    rating: 4,
    stocks: 100,
    inStock: true,
    codAvailable: true,
  },
  {
    _id: uuid(),
    title: "Hublot unicorn",
    company: "Hublot",
    img: "https://res.cloudinary.com/suyash56565656/image/upload/v1648046433/Front-Fist/assets/Products/Hublot/Hublot-2_o2317k.png",
    price: 5000,
    categoryName: "Gent's",
    discount: 10,
    isbadge: "true",
    badge: "New",
    rating: 4,
    stocks: 100,
    inStock: true,
    codAvailable: true,
  },
  {
    _id: uuid(),
    title: "Montblanc stipes",
    company: "Montblanc",
    img: "https://res.cloudinary.com/suyash56565656/image/upload/v1648046434/Front-Fist/assets/Products/Montblanc/montblanc-1_qz6dnr.png",
    price: 5000,
    categoryName: "Gent's",
    discount: 10,
    isbadge: "true",
    badge: "New",
    rating: 4,
    stocks: 100,
    inStock: true,
    codAvailable: true,
  },
  {
    _id: uuid(),
    title: "Montblanc silver",
    company: "Montblanc",
    img: "https://res.cloudinary.com/suyash56565656/image/upload/v1648046435/Front-Fist/assets/Products/Montblanc/montblanc-2_u9wxio.png",
    price: 5000,
    categoryName: "Gent's",
    discount: 10,
    isbadge: "true",
    badge: "New",
    rating: 4,
    stocks: 100,
    inStock: true,
    codAvailable: true,
  },
  {
    _id: uuid(),
    title: "Rolex sailor edition",
    company: "Rolex",
    img: "https://res.cloudinary.com/suyash56565656/image/upload/v1648046437/Front-Fist/assets/Products/Rolex%20watches/Rolex-1_hpflsl.png",
    price: 5000,
    categoryName: "Gent's",
    discount: 10,
    isbadge: "true",
    badge: "New",
    rating: 4,
    stocks: 100,
    inStock: true,
    codAvailable: true,
  },
  {
    _id: uuid(),
    title: "Rolex diamond edition",
    company: "Rolex",
    img: "https://res.cloudinary.com/suyash56565656/image/upload/v1648046439/Front-Fist/assets/Products/Rolex%20watches/Rolex-2_zc1ry0.png",
    price: 5000,
    categoryName: "Gent's",
    discount: 10,
    isbadge: "true",
    badge: "New",
    rating: 4,
    stocks: 100,
    inStock: true,
    codAvailable: true,
  },
  {
    _id: uuid(),
    title: "Smartwatch golden",
    company: "Smartwatch",
    img: "https://res.cloudinary.com/suyash56565656/image/upload/v1648046436/Front-Fist/assets/Products/Smartwatches/smartWatch-1_urhorb.png",
    price: 5000,
    categoryName: "Gent's",
    discount: 10,
    isbadge: "true",
    badge: "Bestseller",
    rating: 4,
    stocks: 100,
    inStock: true,
    codAvailable: true,
  },
  {
    _id: uuid(),
    title: "Smartwatch Black",
    company: "Smartwatch",
    img: "https://res.cloudinary.com/suyash56565656/image/upload/v1648046435/Front-Fist/assets/Products/Smartwatches/smartWatch-2_xz8cgf.png",
    price: 5000,
    categoryName: "Gent's",
    discount: 10,
    isbadge: "true",
    badge: "Sold Out",
    rating: 4,
    stocks: 100,
    inStock: true,
    codAvailable: true,
  },
];
